name: Build

on: [workflow_dispatch, push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 5.15.2
          target: desktop
          arch: win64_msvc2019_64
          cache: true
          cache-key-prefix: install-qt-action

      - name: Configure MSVC (Windows)
        uses: ilammy/msvc-dev-cmd@v1

      - name: Create binary folder
        shell: bash
        run: mkdir ./bin/

      - name: Install Windows Discord RPC
        shell: bash
        run: |
          curl -L https://github.com/discordapp/discord-rpc/releases/download/v3.4.0/discord-rpc-win.zip -o discord_rpc.zip
          unzip discord_rpc.zip
          cp ./discord-rpc/win64-dynamic/lib/discord-rpc.lib ./3rd/discord-rpc/
          cp ./discord-rpc/win64-dynamic/include/discord*.h ./3rd/discord-rpc/
          cp ./discord-rpc/win64-dynamic/bin/discord-rpc.dll ./bin/
          
      - name: Install Windows BASS
        shell: bash
        run: |
          curl http://www.un4seen.com/files/bass24.zip -o bass.zip
          unzip -d bass -o bass.zip
          cp ./bass/c/bass.h ./3rd/bass
          cp ./bass/c/x64/bass.lib ./3rd/bass
          cp ./bass/x64/bass.dll ./bin/

          curl http://www.un4seen.com/files/bassopus24.zip -o bassopus.zip
          unzip -d bass -o bassopus.zip
          cp ./bass/c/bassopus.h ./3rd/bass
          cp ./bass/c/x64/bassopus.lib ./3rd/bass
          cp ./bass/x64/bassopus.dll ./bin/

          curl https://www.un4seen.com/files/z/0/bass_fx24.zip -o bassfx.zip
          unzip -d bass -o bassfx.zip
          cp ./bass/c/bass_fx.h ./3rd/bass
          cp ./bass/c/x64/bass_fx.lib ./3rd/bass
          cp ./bass/x64/bass_fx.dll ./bin/

      - name: Install sol2
        shell: bash
        run: |
          curl -L https://github.com/ThePhD/sol2/releases/download/v3.3.0/config.hpp -o ./3rd/sol/config.hpp
          curl -L https://github.com/ThePhD/sol2/releases/download/v3.3.0/forward.hpp -o ./3rd/sol/forward.hpp
          curl -L https://github.com/ThePhD/sol2/releases/download/v3.3.0/sol.hpp -o ./3rd/sol/sol.hpp

      - name: Install LUA 5.4
        shell: bash
        run: |
          curl https://master.dl.sourceforge.net/project/luabinaries/5.4.2/Windows%20Libraries/Dynamic/lua-5.4.2_Win64_dll16_lib.zip?viasf=1 -o lua.zip
          unzip -d lua -o lua.zip

          cp ./lua/lua54.dll ./bin/
          cp ./lua/lua54.lib ./3rd/lua
          cp ./lua/include/* ./3rd/lua 

      - name: Install stb_image_resize
        shell: bash
        run: |
          curl https://raw.githubusercontent.com/nothings/stb/refs/heads/master/stb_image_resize2.h -o ./3rd/stb_image_resize2.h


      - name: Clone Apng plugin
        uses: actions/checkout@v4
        with:
          repository: jurplel/QtApng
          path: ./qtapng

      - name: Build Apng plugin
        run: |
          cd ./qtapng
          cmake . -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE="${{ github.workspace }}/bin/imageformats/" -DAPNG_QT6=OFF
          cmake --build . --config Release

      - name: Build
        run: |
          cmake . -D CMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Deploy Windows
        working-directory: ${{github.workspace}}/bin/
        shell: bash
        run: |
          windeployqt --no-quick-import --no-translations --no-compiler-runtime --no-opengl-sw ./dro-client.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DRO-Client-Windows
          path: ${{github.workspace}}/bin